name: Schedule Python Script

on:
  schedule:
    - cron: '0 13 * * 1-5'  
    - cron: '0 14 * * 1-5'  
    - cron: '0 15 * * 1-5'  
    - cron: '0 16 * * 1-5'  

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium  
    - name: Run script
      run: python food_bank_monitor.py
